const newRequest = {
  Primary_Offence: "asdasd",
  Occurrence_Year: null,
  Occurrence_Month: null,
  Occurrence_DayOfWeek: null,
  Occurrence_DayOfMonth: null,
  Occurrence_Hour: null,
  Report_Year: null,
  Report_Month: null,
  Report_DayOfWeek: null,
  Report_DayOfMonth: null,
  Report_Hour: null,
  Division: null,
  City: null,
  Hood_ID: null,
  NeighbourhoodName: null,
  Location_Type: null,
  Premises_Type: null,
  Bike_Make: null,
  Bike_Type: null,
  Bike_Speed: null,
  Bike_Colour: null,
  Cost_of_Bike: null,
  Longitude: null,
  Latitude: null,
  ro_delta: null,
};

export default newRequest